### ISSUE TITLE
DPU paper on google drive (try to run on the zynq board)

### ISSUE THREAD

**Issue by fann9876543210** [jerry20091103/23th-project#22]

**Comment by PaulWang0513** [comment]
Successfully boot the zynq board and connect to PC.

Try to go through the tutorial but encounter an error at the first step
![image](https://user-images.githubusercontent.com/65814684/183259129-3895b79d-a380-4f6b-9c14-9f66724476d2.png)

**Comment by PaulWang0513** [comment]
用台北家裡的網路沒有遇到上面的問題，有成功跑起來了

**Comment by PaulWang0513** [comment]
see how it work
research on how to modify/re-train the model

**Comment by PaulWang0513** [comment]
successfully compile and run pre-trained models from model zoo
still working on training a new model ... stuck at open jupyter notebook in xilinx docker environment

**Comment by PaulWang0513** [comment]
Although there exist problem to use jupyter notebook, training and compiling model can be done without it!

A self-trained mnist classifier is ready and can be deployed on ZCU104.
However, to test the model, it required to download the dataset to the board ... but the internet problem have not been solved QQ

**Comment by PaulWang0513** [comment]
### Problem solved!
- The self-trained mnist classifier works
- The problem `WNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffb5906c40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')'` is caused by improper DNS setting
- To solve this problem:
    1. Run `resolvectl status` to see current DNS server (192.168.1.1 in this case)
    ![](https://i.imgur.com/WU7jQ93.png =50%x)
    2. Set the nameserver in /etc/resolv.conf
    ![](https://i.imgur.com/ua6pHUd.png)
